builds:
  - id: example
    main: ./cmd
    binary: lark-logger-example
    dir: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

# snapshot:
#   name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: KCNyu
    name: lark-logger
  draft: false
  prerelease: false
  mode: replace

# dockers:
#   - image_templates:
#       - "kcnyu/lark-logger:{{ .Version }}"
#       - "kcnyu/lark-logger:latest"
#     dockerfile: Dockerfile
#     goos: linux
#     goarch: amd64

